In [1]:
import numpy as np

#### One dimensional array

In [2]:
one_d=np.array([10,20,30,40])
one_d

array([10, 20, 30, 40])

### Basic Indexing

In [3]:
one_d[2]

30

In [4]:
one_d[-1]

40

In [5]:
a=one_d[2]
a

30

In [6]:
a=99
print (one_d)

[10 20 30 40]

### Slicing one dimensional array

In [61]:
slice1=one_d[0:3:2]
print (slice1)

[77777    30]

### Return type of slicing will be ndarray

In [8]:
type(slice1)

numpy.ndarray

### Modifying slice1 will modify the original array (one_d)

In [9]:
slice1[0]=99999
slice1

array([99999,    30])

In [10]:
one_d

array([99999,    20,    30,    40])

### Modifying original array(one_d) will also modify the array generated by basic slicing(slice1)

In [11]:
one_d[0]=77777
print (one_d)
print (slice1)

[77777    20    30    40]
[77777    30]

In [12]:
one_d[::-2]

array([40, 20])

### Index out of bound --> IndexError

In [13]:
#print (one_d[5])

### Slicing out of bound

In [14]:
print(one_d[5:])

[]

# Two dimensional array

## Creating two dimensional array

In [15]:
two_d=np.array([[0,1,2],[3,4,5],[6,7,8]])
print (two_d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## Basic Indexing--> Two dimensional array

### Accessing particular element

In [16]:
print (two_d[(1,2)])

5

In [17]:
print (two_d[1,2])

5

In [18]:
print (two_d[-1,-1])

8

### Accessing particular row

In [19]:
print (two_d[(1)])

[3 4 5]

In [20]:
type(two_d[(1)])

numpy.ndarray

In [21]:
np.shape(two_d[(1)])

(3,)

### Accessing particular column

In [46]:
print (two_d[:,1])

[1 4 7]

In [23]:
s1=two_d[0:2,1:]
s1

array([[1, 2],
       [4, 5]])

In [24]:
#s1[0]=99999
#s1

In [25]:
two_d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
#two_d[0,1]=88888
#two_d

In [27]:
s1

array([[1, 2],
       [4, 5]])

In [28]:
two_d[::-1,1:]

array([[7, 8],
       [4, 5],
       [1, 2]])

### Index out of bound

In [29]:
#two_d[0,5]

### Slicing out of bound

In [30]:
print (two_d[5:,])

[]

In [48]:
print(two_d[1,:])

[99  4  5]

## Basic Slicing two dimensional array

In [31]:
print (two_d[1:,1:])

[[4 5]
 [7 8]]

In [32]:
print (two_d[0:2,1:])

[[1 2]
 [4 5]]

In [33]:
print (two_d[1:,::2])

[[3 5]
 [6 8]]

# Advanced Indexing

### Integer Array Indexing

In [34]:
print (two_d[[0,1,2],[0,1,2]])

[0 4 8]

In [35]:
print (type(two_d[[0,1,2],[0,1,2]]))

<class 'numpy.ndarray'>

## Three dimensional array

### Creating three dimensional array

In [51]:
three_d=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print (three_d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

In [137]:
np.shape(three_d)

(2, 2, 2)

### Accessing particular element

In [142]:
print (three_d[1,0,1])

5

In [143]:
print (three_d[(1,0,1)])

5

In [150]:
print (three_d[(-1,-1,-1)])

7

### Accessing a particualr matrix(two dimensional array)

In [144]:
print (three_d[(1)])

[[4 5]
 [6 7]]

### Accessing a particular row from the particualr matrix

In [146]:
print (three_d[(1,0)])

[4 5]

### Accessing a particular column from particular matrix

In [148]:
print (three_d[1,:,1])

[5 7]

### Accessing element at same position from each matrix

In [149]:
print (three_d[:,1,1])

[3 7]

## Negative Indexing

In [46]:
three_d[(-1,-1,-1)]

33

### Slicing three dimensional array

In [164]:
print (three_d[:,:,1:])

[[[1]
  [3]]

 [[5]
  [7]]]

### Out of range index

In [167]:
print (three_d[2:,:,:])

[]

## Advanced Indexing

In [184]:
print (three_d[[0,1],[0,1],[0,1]])

[0 7]

In [52]:
print (three_d[:,1,1])

[3 7]

In [58]:
print (three_d[1,1,:])

[6 7]

In [60]:
print (three_d[1,1])

[6 7]